language: node_js
node_js:
    - 0.10
    - 0.12
    - iojs

matrix:
  allow_failures:
    - node_js: 'iojs'

before_install:
  - npm install gulp -g

script:
  - gulp default

notifications:
    email:
        on_success: never
        on_failure: change
